api_platform:
    title: 'API COURSE SYM REACT'
    version: '1.0.4'
    show_webby: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: false
            items_per_page: 12
            client_enabled: true
            client_items_per_page: true
            items_per_page_parameter_name: "count"